auto: true
server: true
permalink: /:title.html

title: Movimento Seinfeld
description: Toda quinta-feira um texto sobre um episódio de Seinfeld, seguindo a ordem em que eles foram ao ar, de Chronicles ao Finale.

authors:
  - name: felipe
    display_name: Seu Felipe
    web: http://seufelipe.com.br
  - name: ronald
    display_name: Ronald Rios
    web: http://ronaldrios.com.br
  - name: ulisses
    display_name: Ulisses Mattos
    web: http://tolisses.com.br
  - name: chicobarney
    display_name: Chico Barney
    web: http://twitter.com/chicobarney
  - name: daniel
    display_name: Daniel Lima
    web: http://generico.interbarney.com
  - name: anderson
    display_name: Anderson Gomes
    web: http://www.rosebudeotreno.com
  - name: moskito
    display_name: Gabriel Von Doscht
    web: http://twitter.com/moskito
  - name: chini
    display_name: Vinícius Perez
    web: http://confrariaonanista.wordpress.com
  - name: arnaldo
    display_name: Arnaldo Branco
    web: http://www.oesquema.com.br/mauhumor
  - name: renata
    display_name: Renata Palladino
  - name: bzirpoli
    display_name: Bernardo Zirpoli
    web: http://twitter.com/bzirpoli
  - name: leojaime
    display_name: Leo Jaime
    web: http://www.leojaime.com.br
  - name: gustavodealmeida
    display_name: Gustavo de Almeida
    web: http://interney.net/blogs/eclipse
  - name: netotorcato
    display_name: Neto Torcato
    web: http://netotorcato.blogspot.com.br
  - name: sergiomaggi
    display_name: Sérgio Maggi
    web: http://oglobo.globo.com/cultura/kogut/series
  - name: castrezana
    display_name: Rodolfo Castrezana
    web: http://omedi.net
  - name: spiceee
    display_name: Fabio Mont Alegre
    web: http://twitter.com/spiceee
  - name: marcelefernandes
    display_name: Marcele Fernandes
    web: http://interney.net/blogs/eclipse
  - name: haroldomourao
    display_name: Haroldo Mourão
    web: http://twitter.com/Oharoldomourao
  - name: cintia
    display_name: Cintia Loureiro
    web: http://cintialoureiro.com.br
  - name: erik
    display_name: Erik Gustavo
    web: http://erikgustavo.com
  - name: danielsansao
    display_name: Daniel Sansão
    web: http://www.danielsansao.com.br
  - name: danielpilon
    display_name: Daniel Pilon
    web: http://www.pilog.kit.net
  - name: rafaelcapanema
    display_name: Rafael Capanema
    web: http://twitter.com/rafaelcapanema
  - name: robertoalmeida
    display_name: Roberto Almeida
    web: http://twitter.com/roberto_alm
  - name: ibere
    display_name: Iberê
    web: http://twitter.com/ibere
  - name: edsonmorais
    display_name: Edson Morais
  - name: henriquecapanema
    display_name: Henrique Capanema
    web: http://twitter.com/capanema
  - name: leoluz
    display_name: Léo Luz
    web: http://twitter.com/leoluz
  - name: mariannagomes
    display_name: Marianna Gomes
  - name: leonardobraganca
    display_name: Leonardo Bragança
  - name: pedrohollanda
    display_name: Pedro Hollanda
    web: http://tallbuildingsshake.tumblr.com
  - name: carbonell
    display_name: Leo Carbonell
    web: http://www.linkedin.com/in/leocarbonell
  - name: doni
    display_name: Marcos Donizetti
    web: http://twitter.com/do_oni
  - name: gustavoguimaraes
    display_name: Gustavo Guimarães
    web: http://twitter.com/gusguimaraes
  - name: pedroadams
    display_name: Pedro Adams
    web: http://twitter.com/pedroadams
  - name: piangers
    display_name: Marcos Piangers
    web: http://twitter.com/piangers
  - name: guslanzetta
    display_name: Gus Lanzetta
    web: http://guslanzetta.com
  - name: rafaelmadeira
    display_name: Rafael Madeira
    web: http://twitter.com/rafaelmadeira
  - name: david
    display_name: David Boutsiavaras
    web: http://twitter.com/zambinos
  - name: joao
    display_name: João Baldi Jr.
    web: http://justwrapped.interbarney.com
  - name: mitsu
    display_name: Gabriel Mitsu
    web: http://mitsudiz.interbarney.com
  - name: marcelocosta
    display_name: Marcelo Costa
    web: http://www.screamyell.com.br
  - name: felipesantoro
    display_name: Felipe Santoro
    web: http://felipesantoro.wordpress.com  
