auto: true
server: true
permalink: /:title.html

title: Movimento Seinfeld
description: Toda quinta-feira um texto sobre um episódio de Seinfeld, seguindo a ordem em que eles foram ao ar, de Chronicles ao Finale.

authors:
  felipe:
    display_name: Seu Felipe
    web: http://seufelipe.com.br
  ronald:
    display_name: Ronald Rios
    web: http://ronaldrios.com.br
  ulisses:
    display_name: Ulisses Mattos
    web: http://tolisses.com.br
  chicobarney:
    display_name: Chico Barney
    web: http://twitter.com/chicobarney
  daniel:
    display_name: Daniel Lima
    web: http://generico.interbarney.com
  anderson:
    display_name: Anderson Gomes
    web: http://www.rosebudeotreno.com
  moskito:
    display_name: Gabriel Von Doscht
    web: http://twitter.com/moskito
  chini:
    display_name: Vinícius Perez
    web: http://confrariaonanista.wordpress.com
  arnaldo:
    display_name: Arnaldo Branco
    web: http://www.oesquema.com.br/mauhumor
  renata:
    display_name: Renata Palladino
  bzirpoli:
    display_name: Bernardo Zirpoli
    web: http://twitter.com/bzirpoli
  leojaime:
    display_name: Leo Jaime
    web: http://www.leojaime.com.br
  gustavodealmeida:
    display_name: Gustavo de Almeida
    web: http://interney.net/blogs/eclipse
  netotorcato:
    display_name: Neto Torcato
    web: http://netotorcato.blogspot.com.br
  sergiomaggi:
    display_name: Sérgio Maggi
    web: http://oglobo.globo.com/cultura/kogut/series
  castrezana:
    display_name: Rodolfo Castrezana
    web: http://omedi.net
  spiceee:
    display_name: Fabio Mont Alegre
    web: http://twitter.com/spiceee
  marcelefernandes:
    display_name: Marcele Fernandes
    web: http://interney.net/blogs/eclipse
  haroldomourao:
    display_name: Haroldo Mourão
    web: http://twitter.com/Oharoldomourao
  cintia:
    display_name: Cintia Loureiro
    web: http://cintialoureiro.com.br
  erik:
    display_name: Erik Gustavo
    web: http://erikgustavo.com
  danielsansao:
    display_name: Daniel Sansão
    web: http://www.danielsansao.com.br
  danielpilon:
    display_name: Daniel Pilon
    web: http://www.pilog.kit.net
  rafaelcapanema:
    display_name: Rafael Capanema
    web: http://twitter.com/rafaelcapanema
  robertoalmeida:
    display_name: Roberto Almeida
    web: http://twitter.com/roberto_alm
  ibere:
    display_name: Iberê
    web: http://twitter.com/ibere
  edsonmorais:
    display_name: Edson Morais
  henriquecapanema:
    display_name: Henrique Capanema
    web: http://twitter.com/capanema
  leoluz:
    display_name: Léo Luz
    web: http://twitter.com/leoluz
  mariannagomes:
    display_name: Marianna Gomes
  leonardobraganca:
    display_name: Leonardo Bragança
  pedrohollanda:
    display_name: Pedro Hollanda
    web: http://tallbuildingsshake.tumblr.com
  carbonell:
    display_name: Leo Carbonell
    web: http://www.linkedin.com/in/leocarbonell
  doni:
    display_name: Marcos Donizetti
    web: http://twitter.com/do_oni
  gustavoguimaraes:
    display_name: Gustavo Guimarães
    web: http://twitter.com/gusguimaraes
  pedroadams:
    display_name: Pedro Adams
    web: http://twitter.com/pedroadams
  piangers:
    display_name: Marcos Piangers
    web: http://twitter.com/piangers
  guslanzetta:
    display_name: Gus Lanzetta
    web: http://guslanzetta.com
  rafaelmadeira:
    display_name: Rafael Madeira
    web: http://twitter.com/rafaelmadeira
  david:
    display_name: David Boutsiavaras
    web: http://twitter.com/zambinos
  joao:
    display_name: João Baldi Jr.
    web: http://justwrapped.interbarney.com
  mitsu:
    display_name: Gabriel Mitsu
    web: http://mitsudiz.interbarney.com
  marcelocosta:
    display_name: Marcelo Costa
    web: http://www.screamyell.com.br
  felipesantoro:
    display_name: Felipe Santoro
    web: http://felipesantoro.wordpress.com  
